### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by julienkosinski** [timiscoding/matrix-rain#1]
Hello @timiscoding!

Thank you very much for the wonderful work here, I do love very much your work and I'd like to use your code as a base for a personal project (some kind of artwork of my resume).
Of course, obviously, if you agree on letting me use it I'm gonna mention your work.

Thanks!

**Comment by timiscoding** [comment]
Hi Julien

I'm glad you found my project useful 🎉I have added the [ISC license](https://github.com/timiscoding/matrix-rain/blob/master/LICENSE.txt) so feel free to use it however you wish. I'm curious to know how you found this repo - was it through codepen or just browsing github?

**Comment by julienkosinski** [comment]
@timiscoding Thanks for the licence! :D
I was searching for matrix rain code on Google and I landed in codepen I think to remember! :)

May I consider the same licence for your other attempts (I could use the P5-DOM attempt 2 version because of the better perf I think)?

**Comment by timiscoding** [comment]
You can consider all versions under the same license.
